package emitter

import (
	"strings"
	"sync"

	"ps4-recomp/pkg/elfloader"
)

// CanonicalShims maps library/kernel symbol names and aliases to host runtime shims.
var CanonicalShims = make(map[string]string, len(knownDirectShims)+len(shimAliases))

func init() {
	for _, name := range knownDirectShims {
		CanonicalShims[name] = "shim_" + name
	}
	for alias, target := range shimAliases {
		CanonicalShims[alias] = target
	}
}

// shimAliases maps symbol aliases, wrappers, and NID overrides to their canonical host shims.
var shimAliases = map[string]string{
	// General
	"__error": "shim_error",
	// C++ ABI guard shims
	"__cxa_guard_acquire": "shim_cxa_guard_acquire",
	"__cxa_guard_release": "shim_cxa_guard_release",
	"__cxa_guard_abort":   "shim_cxa_guard_abort",
	"3GPpjQdAMTw":         "shim_cxa_guard_acquire",
	"9rAeANT2tyE":         "shim_cxa_guard_release",
	"2emaaluWzUw":         "shim_cxa_guard_abort",
	// Direct Memory & VMM
	"sceKernelMapDirectMemory2":       "shim_sceKernelMapDirectMemory",
	"sceKernelMapNamedDirectMemory":   "shim_sceKernelMapDirectMemory",
	"sceKernelMapNamedFlexibleMemory": "shim_sceKernelMapNamedFlexibleMemory",
	"sceKernelReserveVirtualRange":    "shim_sceKernelReserveVirtualRange",
	"IWIBBdTHit4":                     "shim_sceKernelMapFlexibleMemory",
	"mL8NDH86iQI":                     "shim_sceKernelMapNamedFlexibleMemory",
	"7oxv3PPCumo":                     "shim_sceKernelReserveVirtualRange",
	"959qrazPIrg":                     "shim_sceKernelGetProcParam",
	// Libc aliases with leading underscore
	"_exit":           "shim_exit",
	"_fcntl":          "shim_fcntl",
	"_ioctl":          "shim_ioctl",
	"_open":           "shim_open",
	"_read":           "shim_read",
	"_readv":          "shim_readv",
	"_write":          "shim_write",
	"_writev":         "shim_writev",
	"sceKernelMunmap": "shim_munmap",
	// Sysmodule
	"hHrGoGoNf+s": "shim_sceSysmoduleLoadModuleInternalWithArg",
	// libkernel File I/O & System Events
	"sceKernelOpen":     "shim_open",
	"sceKernelClose":    "shim_close",
	"sceKernelRead":     "shim_read",
	"sceKernelWrite":    "shim_write",
	"sceKernelLseek":    "shim_lseek",
	"sceKernelStat":     "shim_stat",
	"sceKernelFstat":    "shim_fstat",
	"sceKernelChmod":    "shim_chmod",
	"sceKernelUtimes":   "shim_utimes",
	"sceKernelGetdents": "shim_getdents",
	// libScePosix BSD Sockets & System
	"__sys_socketex":          "shim_socket",
	"scePthreadRwlockInit":    "shim_pthread_rwlock_init",
	"scePthreadRwlockDestroy": "shim_pthread_rwlock_destroy",
	"scePthreadRwlockRdlock":  "shim_pthread_rwlock_rdlock",
	"scePthreadRwlockWrlock":  "shim_pthread_rwlock_wrlock",
	"scePthreadRwlockUnlock":  "shim_pthread_rwlock_unlock",
	// Kernel File System (pread / preadv)
	"+r3rMFwItV4": "shim_sceKernelPread",
	"yTj62I7kw4s": "shim_sceKernelPreadv",
	// Kernel AIO (Asynchronous I/O)
	"vYU8P9Td2Zo": "shim_sceKernelAioInitializeImpl",
	"nu4a0-arQis": "shim_sceKernelAioInitializeParam",
	"9WK-vhNXimw": "shim_sceKernelAioSetParam",
	"HgX7+AORI58": "shim_sceKernelAioSubmitReadCommands",
	"lXT0m3P-vs4": "shim_sceKernelAioSubmitReadCommandsMultiple",
	"XQ8C8y+de+E": "shim_sceKernelAioSubmitWriteCommands",
	"xT3Cpz0yh6Y": "shim_sceKernelAioSubmitWriteCommandsMultiple",
	"2pOuoWoCxdk": "shim_sceKernelAioPollRequest",
	"o7O4z3jwKzo": "shim_sceKernelAioPollRequests",
	"fR521KIGgb8": "shim_sceKernelAioCancelRequest",
	"3Lca1XBrQdY": "shim_sceKernelAioCancelRequests",
	"5TgME6AYty4": "shim_sceKernelAioDeleteRequest",
	"Ft3EtsZzAoY": "shim_sceKernelAioDeleteRequests",
	"KOF-oJbQVvc": "shim_sceKernelAioWaitRequest",
	"lgK+oIWkJyA": "shim_sceKernelAioWaitRequests",
	// libSceAppContent NIDs and Aliases
	"sceAppContentAddcontEnqueueDownloadByEntitlemetId": "shim_sceAppContentAddcontEnqueueDownloadByEntitlementId",
	"sceAppContentAddcontMountByEntitlemetId":           "shim_sceAppContentAddcontMountByEntitlementId",
	"R9lA82OraNs": "shim_sceAppContentInitialize",
	"buYbeLOGWmA": "shim_sceAppContentTemporaryDataMount2",
	"7bOLX66Iz-U": "shim_sceAppContentTemporaryDataMount",
	"bcolXMmp6qQ": "shim_sceAppContentTemporaryDataUnmount",
	"a5N7lAG0y2Q": "shim_sceAppContentTemporaryDataFormat",
	"SaKib2Ug0yI": "shim_sceAppContentTemporaryDataGetAvailableSpaceKb",
	"Gl6w5i0JokY": "shim_sceAppContentDownloadDataGetAvailableSpaceKb",
	"CN7EbEV7MFU": "shim_sceAppContentDownloadDataFormat",
	"99b82IKXpH4": "shim_sceAppContentAppParamGetInt",
	"+OlXCu8qxUk": "shim_sceAppContentAppParamGetString",
	"m47juOmH0VE": "shim_sceAppContentGetAddcontInfo",
	"xnd8BJzAxmk": "shim_sceAppContentGetAddcontInfoList",
	"XTWR0UXvcgs": "shim_sceAppContentGetEntitlementKey",
	"VANhIWcqYak": "shim_sceAppContentAddcontMount",
	"3rHWaV-1KC4": "shim_sceAppContentAddcontUnmount",
	"ZiATpP9gEkA": "shim_sceAppContentAddcontDelete",
	"7gxh+5QubhY": "shim_sceAppContentAddcontEnqueueDownload",
	"TVM-aYIsG9k": "shim_sceAppContentAddcontEnqueueDownloadSp",
	"D3H+cjfzzFY": "shim_sceAppContentAddcontShrink",
	"gpGZDB4ZlrI": "shim_sceAppContentDownload0Expand",
	"S5eMvWnbbXg": "shim_sceAppContentDownload0Shrink",
	"B5gVeVurdUA": "shim_sceAppContentDownload1Expand",
	"kUeYucqnb7o": "shim_sceAppContentDownload1Shrink",
	"5bvvbUSiFs4": "shim_sceAppContentGetAddcontDownloadProgress",
	"74-1x3lyZK8": "shim_sceAppContentGetRegion",
	"bVtF7v2uqT0": "shim_sceAppContentRequestPatchInstall",
	"9Gq5rOkWzNU": "shim_sceAppContentSmallSharedDataFormat",
	"xhb-r8etmAA": "shim_sceAppContentSmallSharedDataGetAvailableSpaceKb",
	"QuApZnMo9MM": "shim_sceAppContentSmallSharedDataMount",
	"EqMtBHWu-5M": "shim_sceAppContentSmallSharedDataUnmount",
	"xmhnAoxN3Wk": "shim_sceAppContentGetPftFlag",
	"xZo2-418Wdo": "shim_Func_C59A36FF8D7C59DA",
	"kJmjt81mXKQ": "shim_sceAppContentAddcontEnqueueDownloadByEntitlementId",
	"efX3lrPwdKA": "shim_sceAppContentAddcontMountByEntitlementId",
	"z9hgjLd1SGA": "shim_sceAppContentGetAddcontInfoByEntitlementId",
	"3wUaDTGmjcQ": "shim_sceAppContentGetAddcontInfoListByIroTag",
	"TCqT7kPuGx0": "shim_sceAppContentGetDownloadedStoreCountry",
	// libkernel Kernel Semaphores
	"188x57JYp0g": "shim_sceKernelCreateSema",
	"R1Jvn8bSCW8": "shim_sceKernelDeleteSema",
	"Zxa0VhQVTsk": "shim_sceKernelWaitSema",
	"4czppHBiriw": "shim_sceKernelSignalSema",
	"12wOHk8ywb0": "shim_sceKernelPollSema",
	"4DM06U2BNEY": "shim_sceKernelCancelSema",
	// libkernel Pthread Semaphores
	"GEnUkDZoUwY": "shim_scePthreadSemInit",
	"Vwc+L05e6oE": "shim_scePthreadSemDestroy",
	"C36iRE0F5sE": "shim_scePthreadSemWait",
	"H2a+IN9TP0E": "shim_scePthreadSemTrywait",
	"fjN6NQHhK8k": "shim_scePthreadSemTimedwait",
	"aishVAiFaYM": "shim_scePthreadSemPost",
	"DjpBvGlaWbQ": "shim_scePthreadSemGetvalue",
	// libkernel Pthread Attributes & Threading
	"-fA+7ZlGDQs": "shim_scePthreadAttrGetstacksize",
	"Bvn74vj6oLo": "shim_scePthreadAttrSetstack",
	"GBUY7ywdULE": "shim_scePthreadRename",
	"P41kTWUS3EI": "shim_scePthreadGetschedparam",
	"oIRFTjoILbg": "shim_scePthreadSetschedparam",
	// libkernel Direct Memory & VMM
	"DGMG3JshrZU": "shim_sceKernelSetVirtualRangeName",
	"BHouLQzh0X0": "shim_sceKernelDirectMemoryQuery",
	"hwVSPCmp5tM": "shim_sceKernelCheckedReleaseDirectMemory",
	"vSMAm3cxYTY": "shim_sceKernelMprotect",
	// libkernel Event Flag & Event Queue
	"PZku4ZrXJqg": "shim_sceKernelCancelEventFlag",
	"mJ7aghmgvfc": "shim_sceKernelGetEventId",
	"23CPPI1tyBY": "shim_sceKernelGetEventFilter",
	"LJDwdSNTnDg": "shim_sceKernelDeleteUserEvent",
	// libkernel System & Utilities
	"QBi7HCK03hw": "shim_sceKernelClockGettime",
	"Xjoosiw+XPI": "shim_sceKernelUuidCreate",
	"ca7v6Cxulzs": "shim_sceKernelSetGPO",
	"mpxAdqW7dKY": "shim_sceKernelIsProspero",
	// File system aliases
	"sceKernelMkdir":    "shim_mkdir",
	"sceKernelRename":   "shim_rename",
	"sceKernelUnlink":   "shim_unlink",
	"sceKernelTruncate": "shim_truncate",
	"sceKernelMlock":    "shim_mlock",
	// libkernel & POSIX Pthread / Synchronization NIDs
	"14bOACANTBo": "shim_scePthreadOnce",
	"Z4QosVuAsA0": "shim_pthread_once",
	"IafI2PxcPnQ": "shim_scePthreadMutexTimedlock",
	"Io9+nTKXZtA": "shim_pthread_mutex_timedlock",
	"8+s5BzZjxSg": "shim_scePthreadAttrGetaffinity",
	"JaRMy+QcpeU": "shim_scePthreadAttrGetdetachstate",
	"x1X76arYMxU": "shim_scePthreadAttrGet",
	"How7B8Oet6k": "shim_scePthreadGetname",
	"0D4-FVvEikw": "shim_pthread_cancel",
	"5txKfcMUAok": "shim_pthread_mutexattr_setprotocol",
	// libkernel File System NIDs
	"1-LFLmRFxxM": "shim_mkdir",
	"c7ZnT7V1B98": "shim_rmdir",
	"52NcYU9+lEo": "shim_rename",
	"AUXVxWeJU-A": "shim_unlink",
	"WlyEA-sLDf0": "shim_truncate",
	"3k6kx-zOOSQ": "shim_mlock",
	// libkernel RTLD, Atexit & Memory NIDs
	"kbw4UHHSYy0": "shim___pthread_cxa_finalize",
	"-o5uEDpN+oY": "shim_sceKernelConvertUtcToLocaltime",
	"0NTHN1NKONI": "shim_sceKernelConvertLocaltimeToUtc",
	"-YTW+qXc3CQ": "shim_sceKernelInternalMemoryGetModuleSegmentInfo",
	"RpQJJVKTiFM": "shim_sceKernelGetModuleInfoForUnwind",
	"f7KBOafysXo": "shim_sceKernelGetModuleInfoFromAddr",
	"Wl2o5hOVZdw": "shim_sceKernelPrintBacktraceWithModuleInfo",
	"OMDRKKAZ8I4": "shim_sceKernelDebugRaiseException",
	"zE-wXIZjLoM": "shim_sceKernelDebugRaiseExceptionOnReleaseMode",
	"il03nluKfMk": "shim_sceKernelRaiseException",
	"WkwEd3N7w0Y": "shim_sceKernelInstallExceptionHandler",
	"8OnWXlgQlvo": "shim__sceKernelRtldThreadAtexitDecrement",
	"Tz4RNUCBbGI": "shim__sceKernelRtldThreadAtexitIncrement",
	"WhCc1w3EhSI": "shim__sceKernelSetThreadAtexitReport",
	"pB-yGZ2nQ9o": "shim__sceKernelSetThreadAtexitCount",
	"rNhWz+lvOMU": "shim__sceKernelSetThreadDtors",
	"p5EcQeEeJAE": "shim__sceKernelRtldSetApplicationHeapAPI",
	"bnZxYgAFeA0": "shim_sceKernelGetSanitizerNewReplaceExternal",
	"py6L8jiVAN8": "shim_sceKernelGetSanitizerMallocReplaceExternal",
	"jh+8XiK4LeE": "shim_sceKernelIsAddressSanitizerEnabled",
	"Fjc4-n1+y2g": "shim___elf_phdr_match_addr",
	"VADc3MNQ3cM": "shim_signal",
	"crb5j7mkk1c": "shim__is_signal_return",
	"djxxOmW6-aw": "shim___progname",
	"lbQKqsERhtE": "shim_sceDiscMapIsRequestOnHDD",
	// Libc Heap Trace Info
	"NWtTN10cJzE": "shim_sceLibcHeapGetTraceInfo",
	// libSceRtc NIDs
	"BtqmpTRXHgk": "shim_sceRtcGetTime_t",
	"NxEI1KByvCI": "shim_sceRtcParseDateTime",
	"zO9UL3qIINQ": "shim_sceRtcGetCurrentNetworkTick",
}

// knownDirectShims contains symbol names whose host shim is "shim_" + name.
var knownDirectShims = []string{
	// General
	"sceKernelUsleep",
	"sysconf",
	"open",
	"fcntl",
	"mmap",
	"munmap",
	"madvise",
	"sigprocmask",
	"sigaction",
	"fstat",
	"close",
	"read",
	"readv",
	"write",
	"writev",
	"ioctl",
	"nanosleep",
	"lseek",
	"exit",
	"poll",
	"raise",
	"pthread_sigmask",
	"cpuset_getaffinity",
	"getrlimit",
	"sched_yield",
	"pthread_create",
	"pthread_join",
	"pthread_detach",
	"pthread_self",
	"pthread_equal",
	"pthread_once",
	"pthread_key_create",
	"pthread_setspecific",
	"pthread_getspecific",
	"pthread_mutex_init",
	"pthread_mutex_lock",
	"pthread_mutex_trylock",
	"pthread_mutex_unlock",
	"pthread_mutex_destroy",
	"pthread_mutexattr_init",
	"pthread_mutexattr_settype",
	"pthread_mutexattr_destroy",
	"pthread_cond_init",
	"pthread_cond_wait",
	"pthread_cond_timedwait",
	"pthread_cond_signal",
	"pthread_cond_broadcast",
	"pthread_cond_destroy",
	"pthread_rwlock_rdlock",
	"pthread_rwlock_wrlock",
	"pthread_rwlock_unlock",
	"syscall",
	// Orbis Pthread threading & synchronization
	"scePthreadCreate",
	"scePthreadJoin",
	"scePthreadDetach",
	"scePthreadExit",
	"scePthreadSelf",
	"scePthreadEqual",
	"scePthreadYield",
	"scePthreadGetthreadid",
	"scePthreadSetprio",
	"scePthreadGetprio",
	"scePthreadSetaffinity",
	"scePthreadGetaffinity",
	"scePthreadAttrInit",
	"scePthreadAttrDestroy",
	"scePthreadAttrSetstacksize",
	"scePthreadAttrSetdetachstate",
	"scePthreadAttrSetschedpolicy",
	"scePthreadAttrSetschedparam",
	"scePthreadAttrGetschedparam",
	"scePthreadAttrSetinheritsched",
	"scePthreadAttrSetaffinity",
	"scePthreadAttrGetstacksize",
	"scePthreadAttrSetstack",
	"scePthreadRename",
	"scePthreadGetschedparam",
	"scePthreadSetschedparam",
	"scePthreadSemInit",
	"scePthreadSemDestroy",
	"scePthreadSemWait",
	"scePthreadSemTrywait",
	"scePthreadSemTimedwait",
	"scePthreadSemPost",
	"scePthreadSemGetvalue",
	"scePthreadMutexInit",
	"scePthreadMutexLock",
	"scePthreadMutexTrylock",
	"scePthreadMutexUnlock",
	"scePthreadMutexDestroy",
	"scePthreadMutexattrInit",
	"scePthreadMutexattrDestroy",
	"scePthreadMutexattrSettype",
	"scePthreadMutexattrSetprotocol",
	"pthread_mutex_timedlock",
	"pthread_cancel",
	"pthread_mutexattr_setprotocol",
	"scePthreadOnce",
	"scePthreadMutexTimedlock",
	"scePthreadAttrGetaffinity",
	"scePthreadAttrGetdetachstate",
	"scePthreadAttrGet",
	"scePthreadGetname",
	"scePthreadCondInit",
	"scePthreadCondDestroy",
	"scePthreadCondSignal",
	"scePthreadCondBroadcast",
	"scePthreadCondWait",
	"scePthreadCondTimedwait",
	"scePthreadCondattrInit",
	"scePthreadCondattrDestroy",
	"scePthreadKeyCreate",
	"scePthreadKeyDelete",
	"scePthreadSetspecific",
	"scePthreadGetspecific",
	"__tls_get_addr",
	// Orbis Event Flags
	"sceKernelCreateEventFlag",
	"sceKernelDeleteEventFlag",
	"sceKernelSetEventFlag",
	"sceKernelClearEventFlag",
	"sceKernelWaitEventFlag",
	"sceKernelPollEventFlag",
	"sceKernelCancelEventFlag",
	// Orbis Timers & CPU Configuration
	"sceKernelGetProcessTimeCounter",
	"sceKernelGetProcessTimeCounterFrequency",
	"sceKernelGetProcessTime",
	"sceKernelGetTscFrequency",
	"sceKernelReadTsc",
	"sceKernelGettimeofday",
	"sceKernelGetCurrentCpu",
	"sceKernelGetCpumode",
	"sceKernelIsNeoMode",
	"sceKernelHasNeoMode",
	"sceKernelIsAuthenticNeo",
	"sceKernelGetSystemSwVersion",
	"sceKernelClockGettime",
	"sceKernelUuidCreate",
	"sceKernelSetGPO",
	"sceKernelIsProspero",
	// File system
	"mkdir",
	"rmdir",
	"rename",
	"truncate",
	"mlock",
	// RTLD, Atexit & Memory
	"__pthread_cxa_finalize",
	"_sceKernelRtldThreadAtexitDecrement",
	"_sceKernelRtldThreadAtexitIncrement",
	"_sceKernelSetThreadAtexitReport",
	"_sceKernelSetThreadAtexitCount",
	"_sceKernelSetThreadDtors",
	"_sceKernelRtldSetApplicationHeapAPI",
	"sceLibcHeapGetTraceInfo",
	"__elf_phdr_match_addr",
	"signal",
	"_is_signal_return",
	"__progname",
	"sceDiscMapIsRequestOnHDD",
	"sceKernelGetSanitizerNewReplaceExternal",
	"sceKernelGetSanitizerMallocReplaceExternal",
	"sceKernelIsAddressSanitizerEnabled",
	"sceKernelInstallExceptionHandler",
	"sceKernelRaiseException",
	"sceKernelDebugRaiseException",
	"sceKernelDebugRaiseExceptionOnReleaseMode",
	"sceKernelPrintBacktraceWithModuleInfo",
	"sceKernelInternalMemoryGetModuleSegmentInfo",
	"sceKernelGetModuleInfoForUnwind",
	"sceKernelGetModuleInfoFromAddr",
	"sceKernelConvertUtcToLocaltime",
	"sceKernelConvertLocaltimeToUtc",
	// RTC
	"sceRtcGetTime_t",
	"sceRtcParseDateTime",
	"sceRtcGetCurrentNetworkTick",
	// every module uses one implementation that copies through mem_base.
	"memcpy",
	"memmove",
	"memset",
	"strlen",
	"strcpy",
	"strncpy",
	"strcmp",
	// Direct Memory & VMM
	"sceKernelAllocateDirectMemory",
	"sceKernelAllocateMainDirectMemory",
	"sceKernelGetDirectMemorySize",
	"sceKernelAvailableDirectMemorySize",
	"sceKernelMapDirectMemory",
	"sceKernelReleaseDirectMemory",
	"sceKernelCheckedReleaseDirectMemory",
	"sceKernelDirectMemoryQuery",
	"sceKernelMapFlexibleMemory",
	"sceKernelMapNamedFlexibleMemory",
	"sceKernelReserveVirtualRange",
	"sceKernelSetVirtualRangeName",
	"sceKernelMprotect",
	"sceKernelConfiguredFlexibleMemorySize",
	"sceKernelAvailableFlexibleMemorySize",
	"sceKernelVirtualQuery",
	"sceKernelQueryMemoryProtection",
	"sceKernelMemoryPoolReserve",
	"sceKernelMemoryPoolExpand",
	"sceKernelMemoryPoolCommit",
	"sceKernelMemoryPoolDecommit",
	"sceKernelGetProcParam",
	// Orbis Kernel Semaphores
	"sceKernelCreateSema",
	"sceKernelDeleteSema",
	"sceKernelWaitSema",
	"sceKernelSignalSema",
	"sceKernelPollSema",
	"sceKernelCancelSema",
	// Event Queue
	"sceKernelCreateEqueue",
	"sceKernelDeleteEqueue",
	"sceKernelWaitEqueue",
	"sceKernelGetEventId",
	"sceKernelGetEventFilter",
	"sceKernelDeleteUserEvent",
	// VideoOut display
	"sceVideoOutOpen",
	"sceVideoOutClose",
	"sceVideoOutSetBufferAttribute",
	"sceVideoOutRegisterBuffers",
	"sceVideoOutSetFlipRate",
	"sceVideoOutAddFlipEvent",
	"sceVideoOutSubmitFlip",
	"sceVideoOutGetFlipStatus",
	"sceVideoOutGetResolutionStatus",
	"sceVideoOutIsFlipPending",
	"sceVideoOutUnregisterBuffers",
	// Stack Protector
	"__stack_chk_fail",
	// Time & Resource
	"clock_gettime",
	"gettimeofday",
	"getrusage",
	// Pthread attributes & sched
	"pthread_attr_init",
	"pthread_attr_destroy",
	"pthread_attr_setdetachstate",
	"pthread_attr_setstacksize",
	"pthread_getschedparam",
	"pthread_setschedparam",
	"pthread_setcanceltype",
	"sched_get_priority_max",
	"sched_get_priority_min",
	// POSIX Semaphores
	"sem_init",
	"sem_destroy",
	"sem_wait",
	"sem_trywait",
	"sem_post",
	"sem_getvalue",
	// AudioOut
	"sceAudioOutInit",
	"sceAudioOutOpen",
	"sceAudioOutOutput",
	"sceAudioOutClose",
	// User Service & System Service
	"sceUserServiceInitialize",
	"sceUserServiceGetInitialUser",
	"sceUserServiceGetLoginUserIdList",
	"sceUserServiceGetUserName",
	"sceUserServiceGetEvent",
	"sceUserServiceTerminate",
	"sceSystemServiceParamGetInt",
	"sceSystemServiceParamGetString",
	"sceSystemServiceHideSplashScreen",
	"sceSystemServiceGetStatus",
	"sceSystemServiceGetDisplaySafeAreaInfo",
	"sceSystemServiceReceiveEvent",
	// PlayGo
	"scePlayGoInitialize",
	"scePlayGoTerminate",
	"scePlayGoOpen",
	"scePlayGoClose",
	"scePlayGoGetProgress",
	"scePlayGoGetLocus",
	"scePlayGoGetLanguageMask",
	"scePlayGoSetLanguageMask",
	"scePlayGoGetInstallSpeed",
	"scePlayGoSetInstallSpeed",
	"scePlayGoGetToDoList",
	"scePlayGoGetEta",
	"scePlayGoPrefetch",
	// RTC (Real Time Clock)
	"sceRtcGetCurrentTick",
	"sceRtcGetTick",
	"sceRtcSetTick",
	"sceRtcGetTickResolution",
	"sceRtcGetCurrentClockLocalTime",
	"sceRtcGetDayOfWeek",
	"sceRtcIsLeapYear",
	// Random
	"sceRandomGetRandomNumber",
	// Pad Subsystem
	"scePadInit",
	"scePadOpen",
	"scePadClose",
	"scePadReadState",
	"scePadRead",
	"scePadGetHandle",
	// Keyboard Subsystem
	"sceKeyboardInit",
	"sceKeyboardOpen",
	"sceKeyboardClose",
	"sceKeyboardReadState",
	"sceKeyboardGetKey2Char",
	"sceKeyboardGetHandle",
	// Sysmodule
	"sceSysmoduleLoadModule",
	"sceSysmoduleIsLoaded",
	"sceSysmoduleUnloadModule",
	"sceSysmoduleLoadModuleInternal",
	"sceSysmoduleUnloadModuleInternal",
	"sceSysmoduleLoadModuleInternalWithArg",
	// FreeType
	"FT_Init_FreeType",
	"FT_New_Face",
	"FT_Set_Pixel_Sizes",
	"FT_Get_Char_Index",
	"FT_Load_Glyph",
	"FT_Render_Glyph",
	// CommonDialog & MsgDialog
	"sceCommonDialogInitialize",
	"sceCommonDialogIsUsed",
	"sceMsgDialogInitialize",
	"sceMsgDialogOpen",
	"sceMsgDialogGetResult",
	"sceMsgDialogGetStatus",
	"sceMsgDialogUpdateStatus",
	"sceMsgDialogClose",
	"sceMsgDialogTerminate",
	"sceMsgDialogProgressBarInc",
	"sceMsgDialogProgressBarSetMsg",
	"sceMsgDialogProgressBarSetValue",
	// libSceImeDialog
	"sceImeDialogInit",
	"sceImeDialogGetStatus",
	"sceImeDialogGetResult",
	"sceImeDialogAbort",
	"sceImeDialogTerm",
	"sceImeDialogGetPanelSizeExtended",
	// libSceSaveDataDialog
	"sceSaveDataDialogInitialize",
	"sceSaveDataDialogOpen",
	"sceSaveDataDialogUpdateStatus",
	"sceSaveDataDialogGetStatus",
	"sceSaveDataDialogGetResult",
	"sceSaveDataDialogTerminate",
	// libSceErrorDialog
	"sceErrorDialogInitialize",
	"sceErrorDialogOpen",
	"sceErrorDialogUpdateStatus",
	"sceErrorDialogGetStatus",
	"sceErrorDialogTerminate",
	// libSceInvitationDialog
	"sceInvitationDialogInitialize",
	"sceInvitationDialogOpenA",
	"sceInvitationDialogUpdateStatus",
	"sceInvitationDialogGetStatus",
	"sceInvitationDialogGetResultA",
	"sceInvitationDialogTerminate",
	// libSceNpProfileDialog
	"sceNpProfileDialogInitialize",
	"sceNpProfileDialogOpenA",
	"sceNpProfileDialogUpdateStatus",
	"sceNpProfileDialogGetStatus",
	"sceNpProfileDialogGetResult",
	"sceNpProfileDialogTerminate",
	// libSceVideoRecording
	"sceVideoRecordingQueryMemSize2",
	"sceVideoRecordingOpen2",
	"sceVideoRecordingClose",
	"sceVideoRecordingStart",
	"sceVideoRecordingStop",
	"sceVideoRecordingGetStatus",
	"sceVideoRecordingSetInfo",
	// libSceScreenShot
	"sceScreenShotEnable",
	"sceScreenShotDisable",
	// libSceSharePlay
	"sceSharePlayInitialize",
	"sceSharePlayTerminate",
	"sceSharePlaySetProhibition",
	// libSceMouse
	"sceMouseInit",
	"sceMouseOpen",
	"sceMouseClose",
	"sceMouseRead",
	// NpTrophy
	"sceNpTrophyInit",
	"sceNpTrophyTerm",
	"sceNpTrophyCreateContext",
	"sceNpTrophyDestroyContext",
	"sceNpTrophyCreateHandle",
	"sceNpTrophyDestroyHandle",
	"sceNpTrophyRegisterContext",
	"sceNpTrophyUnlockTrophy",
	"sceNpTrophyShowTrophyList",
	// Dynamic Module Loader
	"sceKernelLoadStartModule",
	"sceKernelDlsym",
	// libkernel File I/O & System Events
	"sceKernelTriggerUserEvent",
	"sceKernelAddUserEventEdge",
	"sceKernelStopUnloadModule",
	"sceKernelGetPrtAperture",
	// libScePosix BSD Sockets & System
	"socket",
	"connect",
	"bind",
	"listen",
	"accept",
	"send",
	"recv",
	"sendto",
	"recvfrom",
	"setsockopt",
	"getsockopt",
	"getsockname",
	"getpeername",
	"shutdown",
	"select",
	"inet_pton",
	"usleep",
	"stat",
	"getpid",
	"pthread_exit",
	"pthread_key_delete",
	"pthread_rwlock_init",
	"pthread_rwlock_destroy",
	"pthread_rename_np",
	"pthread_create_name_np",
	"unlink",
	// Pad Subsystem additional methods
	"scePadSetVibration",
	"scePadGetControllerInformation",
	"scePadSetLightBar",
	"scePadResetOrientation",
	"scePadResetLightBar",
	// VideoOut additional methods
	"sceVideoOutGetVblankStatus",
	"sceVideoOutGetDeviceCapabilityInfo_",
	"sceVideoOutModeSetAny_",
	// libSceNet Shims
	"sceNetInit",
	"sceNetTerm",
	"sceNetErrnoLoc",
	"sceNetSocket",
	"sceNetSocketClose",
	"sceNetBind",
	"sceNetListen",
	"sceNetAccept",
	"sceNetConnect",
	"sceNetSend",
	"sceNetRecv",
	"sceNetSendto",
	"sceNetRecvfrom",
	"sceNetSetsockopt",
	"sceNetGetsockopt",
	"sceNetGetsockname",
	"sceNetGetpeername",
	"sceNetShutdown",
	"sceNetHtons",
	"sceNetHtonl",
	"sceNetHtonll",
	"sceNetNtohs",
	"sceNetNtohl",
	"sceNetNtohll",
	"sceNetInetPton",
	"sceNetInetNtop",
	"sceNetPoolCreate",
	"sceNetPoolDestroy",
	"sceNetResolverCreate",
	"sceNetResolverDestroy",
	"sceNetResolverStartNtoa",
	"sceNetResolverStartAton",
	"sceNetResolverStartNtoaMultipleRecords",
	"sceNetEpollCreate",
	"sceNetEpollDestroy",
	"sceNetEpollControl",
	"sceNetEpollWait",
	"sceNetGetMacAddress",
	"sceNetGetSockInfo",
	// libSceHttp & libSceHttp2
	"sceHttpInit",
	"sceHttpTerm",
	"sceHttpCreateTemplate",
	"sceHttpDeleteTemplate",
	"sceHttpCreateConnectionWithURL",
	"sceHttpDeleteConnection",
	"sceHttpCreateRequestWithURL",
	"sceHttpCreateRequestWithURL2",
	"sceHttpDeleteRequest",
	"sceHttpSendRequest",
	"sceHttpAbortRequest",
	"sceHttpWaitRequest",
	"sceHttpReadData",
	"sceHttpGetStatusCode",
	"sceHttpGetResponseContentLength",
	"sceHttpGetAllResponseHeaders",
	"sceHttpAddRequestHeader",
	"sceHttpSetNonblock",
	"sceHttpGetLastErrno",
	"sceHttpUriParse",
	"sceHttpUriBuild",
	"sceHttpCreateEpoll",
	"sceHttpSetEpoll",
	"sceHttpDestroyEpoll",
	"sceHttp2Init",
	"sceHttp2Term",
	// libSceSsl
	"sceSslInit",
	"sceSslTerm",
	"sceSslGetCaCerts",
	// libSceJson2 C++ mangled symbols
	"_ZN3sce4Json12MemAllocatorC2Ev",
	"_ZN3sce4Json12MemAllocatorD2Ev",
	"_ZN3sce4Json14InitParameter2C1Ev",
	"_ZN3sce4Json14InitParameter212setAllocatorEPNS0_12MemAllocatorEPv",
	"_ZN3sce4Json14InitParameter217setFileBufferSizeEm",
	"_ZN3sce4Json11InitializerC1Ev",
	"_ZN3sce4Json11InitializerD1Ev",
	"_ZN3sce4Json11Initializer10initializeEPKNS0_14InitParameter2E",
	"_ZN3sce4Json11Initializer9terminateEv",
	"_ZN3sce4Json6StringC1EPKc",
	"_ZN3sce4Json6StringD1Ev",
	"_ZNK3sce4Json6String5c_strEv",
	"_ZN3sce4Json5ValueC1Ev",
	"_ZN3sce4Json5ValueD1Ev",
	"_ZN3sce4Json5ValueaSERKS1_",
	"_ZN3sce4Json5ValueC1ERKNS0_6StringE",
	"_ZNK3sce4Json5Value9getStringEv",
	"_ZNK3sce4Json5ValueixEPKc",
	"_ZN3sce4Json6ObjectC1Ev",
	"_ZN3sce4Json6ObjectC1ERKS1_",
	"_ZN3sce4Json6ObjectD1Ev",
	"_ZN3sce4Json6ObjectixERKNS0_6StringE",
	"_ZN3sce4Json6Parser5parseERNS0_5ValueEPKcm",
	// libSceNp (NpManager, NpAuth, NpMatching2, NpSignaling, NpWebApi, NpScore, NpTus, NpCommerce, NpUtility, NpGameIntent)
	"sceNpCheckNpAvailability",
	"sceNpCheckNpAvailabilityA",
	"sceNpCheckPlus",
	"sceNpCreateAsyncRequest",
	"sceNpCreateRequest",
	"sceNpDeleteRequest",
	"sceNpGetAccountCountry",
	"sceNpGetAccountCountryA",
	"sceNpGetAccountDateOfBirth",
	"sceNpGetAccountDateOfBirthA",
	"sceNpGetAccountId",
	"sceNpGetAccountIdA",
	"sceNpGetAccountLanguage",
	"sceNpGetAccountLanguageA",
	"sceNpGetGamePresenceStatus",
	"sceNpGetGamePresenceStatusA",
	"sceNpGetNpId",
	"sceNpGetNpReachabilityState",
	"sceNpGetOnlineId",
	"sceNpGetState",
	"sceNpHasSignedUp",
	"sceNpIsPlusMember",
	"sceNpPollAsync",
	"sceNpWaitAsync",
	"sceNpRegisterStateCallback",
	"sceNpRegisterStateCallbackA",
	"sceNpUnregisterStateCallback",
	"sceNpUnregisterStateCallbackA",
	"sceNpAuthCreateRequest",
	"sceNpAuthCreateAsyncRequest",
	"sceNpAuthDeleteRequest",
	"sceNpAuthGetAuthorizationCode",
	"sceNpAuthGetAuthorizationCodeA",
	"sceNpAuthPollAsync",
	"sceNpAuthWaitAsync",
	"sceNpMatching2Initialize",
	"sceNpMatching2Terminate",
	"sceNpMatching2CreateContext",
	"sceNpMatching2CreateContextA",
	"sceNpSignalingInitialize",
	"sceNpSignalingTerminate",
	"sceNpSignalingCreateContext",
	"sceNpSignalingCreateContextA",
	"sceNpWebApiInitialize",
	"sceNpWebApiTerminate",
	"sceNpWebApiCreateContext",
	"sceNpWebApiCreateContextA",
	"sceNpWebApiDeleteContext",
	"sceNpWebApiCreateRequest",
	"sceNpWebApiSendRequest",
	"sceNpWebApiSendRequest2",
	"sceNpWebApiDeleteRequest",
	"sceNpScoreCreateNpTitleCtx",
	"sceNpScoreCreateNpTitleCtxA",
	"sceNpScoreDeleteNpTitleCtx",
	"sceNpScoreCreateRequest",
	"sceNpScoreDeleteRequest",
	"sceNpScorePollAsync",
	"sceNpScoreWaitAsync",
	"sceNpTusCreateNpTitleCtx",
	"sceNpTusCreateNpTitleCtxA",
	"sceNpTusDeleteNpTitleCtx",
	"sceNpTusCreateRequest",
	"sceNpTusDeleteRequest",
	"sceNpTusPollAsync",
	"sceNpTusWaitAsync",
	"sceNpCommerceDialogInitialize",
	"sceNpCommerceDialogTerminate",
	"sceNpCommerceDialogClose",
	"sceNpCommerceDialogGetStatus",
	"sceNpCommerceDialogGetResult",
	"sceNpCommerceDialogOpen",
	"sceNpUtilityInit",
	"sceNpUtilityTerm",
	"sceNpGameIntentInitialize",
	"sceNpGameIntentTerminate",
	// libSceVoiceQoS
	"sceVoiceQoSInit",
	"sceVoiceQoSInitHQ",
	"sceVoiceQoSEnd",
	"sceVoiceQoSConnect",
	"sceVoiceQoSDisconnect",
	"sceVoiceQoSGetStatus",
	// Kernel File System (pread / preadv)
	"sceKernelPread",
	"sceKernelPreadv",
	// Kernel AIO (Asynchronous I/O)
	"sceKernelAioInitializeImpl",
	"sceKernelAioInitializeParam",
	"sceKernelAioSetParam",
	"sceKernelAioSubmitReadCommands",
	"sceKernelAioSubmitReadCommandsMultiple",
	"sceKernelAioSubmitWriteCommands",
	"sceKernelAioSubmitWriteCommandsMultiple",
	"sceKernelAioPollRequest",
	"sceKernelAioPollRequests",
	"sceKernelAioCancelRequest",
	"sceKernelAioCancelRequests",
	"sceKernelAioDeleteRequest",
	"sceKernelAioDeleteRequests",
	"sceKernelAioWaitRequest",
	"sceKernelAioWaitRequests",
	// libSceAppContent
	"sceAppContentInitialize",
	"sceAppContentAppParamGetInt",
	"sceAppContentAppParamGetString",
	"sceAppContentTemporaryDataMount",
	"sceAppContentTemporaryDataMount2",
	"sceAppContentTemporaryDataUnmount",
	"sceAppContentTemporaryDataFormat",
	"sceAppContentTemporaryDataGetAvailableSpaceKb",
	"sceAppContentDownloadDataGetAvailableSpaceKb",
	"sceAppContentDownloadDataFormat",
	"sceAppContentGetAddcontInfo",
	"sceAppContentGetAddcontInfoList",
	"sceAppContentGetEntitlementKey",
	"sceAppContentAddcontMount",
	"sceAppContentAddcontUnmount",
	"sceAppContentAddcontDelete",
	"sceAppContentAddcontEnqueueDownload",
	"sceAppContentAddcontEnqueueDownloadSp",
	"sceAppContentAddcontShrink",
	"sceAppContentDownload0Expand",
	"sceAppContentDownload0Shrink",
	"sceAppContentDownload1Expand",
	"sceAppContentDownload1Shrink",
	"sceAppContentGetAddcontDownloadProgress",
	"sceAppContentGetRegion",
	"sceAppContentRequestPatchInstall",
	"sceAppContentSmallSharedDataFormat",
	"sceAppContentSmallSharedDataGetAvailableSpaceKb",
	"sceAppContentSmallSharedDataMount",
	"sceAppContentSmallSharedDataUnmount",
	"sceAppContentGetPftFlag",
	"Func_C59A36FF8D7C59DA",
	"sceAppContentAddcontEnqueueDownloadByEntitlementId",
	"sceAppContentAddcontMountByEntitlementId",
	"sceAppContentGetAddcontInfoByEntitlementId",
	"sceAppContentGetAddcontInfoListByIroTag",
	"sceAppContentGetDownloadedStoreCountry",
}

var (
	canonicalNIDMapOnce sync.Once
	canonicalNIDMap     map[string]string
)

func initCanonicalNIDMap() {
	canonicalNIDMap = make(map[string]string, len(CanonicalShims)*2)
	for plain, shim := range CanonicalShims {
		if nid := elfloader.CalculateNID(plain); nid != "" {
			canonicalNIDMap[nid] = shim
		}
		if !strings.HasPrefix(plain, "_") {
			if nid := elfloader.CalculateNID("_" + plain); nid != "" {
				canonicalNIDMap[nid] = shim
			}
		}
	}
}

func nidPrefix(name string) string {
	if i := strings.IndexByte(name, '#'); i >= 0 {
		return name[:i]
	}
	return ""
}

func shimByNID(nid string) (string, bool) {
	if nid == "" {
		return "", false
	}
	canonicalNIDMapOnce.Do(initCanonicalNIDMap)
	shim, ok := canonicalNIDMap[nid]
	return shim, ok
}

// LookupShim looks up a host shim for a symbol name or Sony NID (hash#lib#mod).
func LookupShim(name string) (string, bool) {
	if shim, ok := CanonicalShims[name]; ok {
		return shim, true
	}
	stripped := strings.TrimPrefix(name, "_")
	if shim, ok := CanonicalShims[stripped]; ok {
		return shim, true
	}
	if nid := nidPrefix(name); nid != "" {
		if shim, ok := shimByNID(nid); ok {
			return shim, true
		}
		if resolved, ok := elfloader.ResolveNID(nid); ok {
			if shim, hit := CanonicalShims[resolved]; hit {
				return shim, true
			}
			strippedResolved := strings.TrimPrefix(resolved, "_")
			if shim, hit := CanonicalShims[strippedResolved]; hit {
				return shim, true
			}
		}
	}
	return "", false
}
